version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - prompt-eval-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - prompt-eval-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - prompt-eval-network

networks:
  prompt-eval-network:
    driver: bridge
